spring:
  data:
    mongodb:
      database: moviedb
      host: localhost
      port: 27017

spring.datasource.username: moviedb
spring.datasource.password: nFLhPPKOnkW1FA1e
spring.data.mongodb.auto-index-creation: "true"

server.port: 8082
